app/account/forms.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2020 - Pizarra
"""
from flask_security.forms import Length
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import InputRequired, EqualTo, DataRequired


class ChangePassword(FlaskForm):
    password = PasswordField('New Password', [InputRequired(), EqualTo('confirm', message='Passwords must match'),
                                              Length(min=4, message='Your password is too short')])
    confirm = PasswordField('Repeat Password')


class CreateTeam(FlaskForm):
    name = StringField('Name', id='name', validators=[DataRequired()])

app/account/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2020 - present nimar3
"""

from flask import Blueprint

from app.base.util import verify_logged_in

blueprint = Blueprint(
    'account_blueprint',
    __name__,
    url_prefix='/my-account',
    template_folder='templates',
    static_folder='static'
)

blueprint.before_request(verify_logged_in)

app/account/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2020 - Pizarra
"""
from flask import render_template, request, flash, redirect, url_for, current_app
from flask_login import current_user
from flask_security.utils import _

from app import db
from app.account import blueprint
from app.account.forms import ChangePassword, CreateTeam
from app.base.models import UserBadge, Badge, Team
from app.base.util import random_string, hash_pass


@blueprint.route('/', defaults={'anchor': 'activity'})
@blueprint.route('/<anchor>')
def route_account_home(anchor):
    anchors = ['activity', 'badges', 'classgroup', 'password', 'access-token']
    if anchor is not None and anchor not in anchors:
        return redirect(url_for('account_blueprint.route_account_home', anchor=None))

    return render_template('profile.html', anchor=anchor, activity_stream=activity_stream(), form=ChangePassword(),
                           form_team=CreateTeam())


@blueprint.route('/regenerate-key')
def route_regenerate_key():
    user = current_user
    user.access_token = random_string()
    db.session.add(user)
    db.session.commit()
    flash(_('New Access Token has been generated!'), 'success')

    return redirect(url_for('account_blueprint.route_account_home', anchor='access-token'))


@blueprint.route('/team/join/<key>')
def join_team(key):
    if key is not None:
        # try to find team with key
        team = Team.query.filter_by(key=key).first()
        if team is not None:
            if team != current_user.team:
                # check if team is not full
                if len(team.members) < current_app.config['TEAM_MAX_SIZE']:
                    # set new team to user
                    user_old_team = current_user.team
                    current_user.team = team
                    db.session.add(current_user)
                    db.session.commit()
                    check_for_empty_team(user_old_team)
                    flash(_('You joined Team {}').format(team.name), 'success')
                else:
                    flash(_('You are unable to join team {} because is full').format(team.name), 'error')
            else:
                flash(_('You already belong to team {}').format(team.name), 'error')
        else:
            flash(_('Team with key {} was not found').format(key), 'error')

    return redirect(url_for('account_blueprint.route_account_home', anchor='activity'))


@blueprint.route('/team/leave')
def leave_team():
    if current_user.team is not None:
        user_old_team = current_user.team
        current_user.team = None
        db.session.add(current_user)
        db.session.commit()
        check_for_empty_team(user_old_team)
        flash(_('You left the team successfully'), 'success')

    return redirect(url_for('account_blueprint.route_account_home', anchor='activity'))


@blueprint.route('/team/create', methods=['POST'])
def create_team():
    if current_user.team is not None:
        flash(_('You cannot create a new Team until you leave your current one'), 'error')
    else:
        team_name = request.form['name']
        team = Team.query.filter_by(name=team_name).first()
        if team is not None:
            flash(_('Team with name {} already exist, please pick another one').format(team.name), 'error')
        else:
            team = Team()
            team.name = team_name
            db.session.add(team)
            db.session.commit()
            current_user.team = team
            db.session.add(current_user)
            db.session.commit()
            flash(_('You created and joined the team {}').format(team.name), 'success')

    return redirect(url_for('account_blueprint.route_account_home', anchor='activity'))


@blueprint.route('/update-password', methods=['POST'])
def route_update_password():
    form = ChangePassword(request.form)

    if form.validate():
        user = current_user
        user.password = hash_pass(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash(_('Password has been updated!'), 'success')
    else:
        flash(_('Unable to update password'), 'error')

    return render_template('profile.html', anchor='password', activity_stream=activity_stream(), form=form,
                           form_team=CreateTeam())


def activity_stream():
    """builds the dict for showing the activity of the user in his profile"""

    # first entrance is the user registered time
    stream = {current_user.registered_at.strftime('%Y-%m-%d'): [
        {'time': current_user.registered_at.strftime('%X'),
         'type': 'registered'}
    ]}

    # TODO move to smaller functions and reuse code
    # add all requests
    for user_request in current_user.requests:
        request_date = user_request.timestamp.strftime('%Y-%m-%d')
        item = {'time': user_request.timestamp.strftime('%X'),
                'type': 'request',
                'object': user_request
                }

        if request_date not in stream:
            stream[request_date] = [item]
        else:
            stream[request_date].append(item)

    # add all badges
    user_badges = UserBadge.query.filter_by(user_id=current_user.id).all()
    for user_badge in user_badges:
        item_date = user_badge.timestamp.strftime('%Y-%m-%d')
        item = {'time': user_badge.timestamp.strftime('%X'),
                'type': 'badge',
                'object': Badge.query.filter_by(id=user_badge.badge_id).first()
                }

        if item_date not in stream:
            stream[item_date] = [item]
        else:
            stream[item_date].append(item)

    return stream


def check_for_empty_team(team):
    if team is not None and len(team.members) == 0:
        db.session.delete(team)
        db.session.commit()

app/account/templates/_profile_about_me.html
<!-- About Me Box -->
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">{{ _('About Me') }}</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <strong><i class="fa fa-book margin-r-5"></i> {{ _('Education') }}</strong>

        <p class="text-muted">
            {{ _('You are enroled in') }} <a
                href="{{ url_for('account_blueprint.route_account_home', anchor='classgroup') }}"><b>{{ current_user.classgroup.description }}</b></a>
        </p>

        <hr>

        <strong><i class="fa fa-map-marker margin-r-5"></i> {{ _('Location') }}</strong>

        <p class="text-muted">{{ _('Space') }} <i class="fa fa-fw fa-rocket"></i></p>

        <hr>

        {% set team = current_user.team %}
        <strong><i class="fa fa-group margin-r-5"></i> {{ _('Team') }} </strong>{{ team.name }}
        {% if team != None %}
            <!-- /.box-header -->
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-toggle="modal" data-target="#modal-leave-team">
                    <i class="fa fa-trash"></i>
                </button>
            </div>
        {% endif %}
        <div class="box-body no-padding">
            {% if team != None %}
                <ul class="users-list clearfix">
                    {% for member in team.members %}
                        <li>
                            <img src="{{ url_for('base_blueprint.static', filename=STATIC_PZ + member.avatar) }}"
                                 alt="{{ _('User Avatar') }}">
                            <a class="users-list-name"
                               href="#">{{ _('You!') if member == current_user else member.name }} </a>
                            <span class="users-list-date">{{ member.username }}</span>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="text-muted">{{ _('Seems like you are not part of a team') }}</p>
                <form class="form-horizontal" action="{{ url_for('account_blueprint.create_team') }}" method="POST"
                      name="create_team_form">
                    <div class="form-group">
                        <div class="col-sm-12">
                            {{ form_team.name(placeholder="new team name", class="form-control", class="form-control text-lowercase") }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit"
                                    class="btn btn-primary btn-block">{{ _('Create a new Team') }}</button>
                        </div>
                    </div>
                </form>
            {% endif %}
            <!-- /.users-list -->
        </div>
        {% if team != None %}
            <div class="box-body no-padding">
                <p>
                    <button type="button" data-toggle="tooltip"
                            data-original-title="{{ _('Share Team URL for others to join') }}"
                            class="btn btn-box-tool"><i
                            class="fa fa-share" onclick="copyTextToClipboard(document.getElementById('team-code'))"></i>
                    </button>
                    <code id="team-code">{{ request.host_url[:-1] + url_for('account_blueprint.join_team', key=team.key) }}</code>
                </p>
            </div>
        {% endif %}
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->

{% if team != None %}
    <div class="modal modal-danger fade" id="modal-leave-team">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="{{ _('Close') }}">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{{ _('Leaving Team') }}</h4>
                </div>
                <div class="modal-body">
                    <p>{{ _('Are you sure you want to leave this team?') }}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline pull-left"
                            data-dismiss="modal">{{ _('Close') }}</button>
                    <a href="{{ url_for('account_blueprint.leave_team') }}" class="btn btn-outline">
                        {{ _('Leave') }}</a>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
{% endif %}

app/account/templates/_profile_resume.html
<!-- Profile Resume -->
<div class="box box-primary">
    <div class="box-body box-profile">
        <img class="profile-user-img img-responsive img-circle"
             src="{{ url_for('base_blueprint.static', filename=STATIC_PZ + current_user.avatar) }}"
             alt="{{ _('User Avatar') }}">

        <h3 class="profile-username text-center">
            {{ current_user.username }}
        </h3>

        <p class="text-muted text-center">
            {{ current_user.email }}
        </p>

        <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
                <b>{{ _('Group Members') }}</b> <a class="pull-right" href="#">
                {{ current_user.classgroup.students | count }}</a>
            </li>
            <li class="list-group-item">
                <b>{{ _('Badges') }}</b> <a class="pull-right">{{ current_user.badges | count }}</a>
            </li>
            <li class="list-group-item">
                <b>{{ _('Requests') }}</b> <a class="pull-right"
                                              href="{{ url_for('home_blueprint.requests') }}">
                {{ current_user.requests | count }}</a>
            </li>
            <li class="list-group-item">
                <b>{{ _('Points') }}</b> <a class="pull-right" href="#">
                {{ current_user.points }}</a>
            </li>
            <li class="list-group-item">
                <b>{{ _('Quota') }}</b> <a class="pull-right">{{ current_user.quota_used }}
                / {{ current_user.quota }}</a>
            </li>
        </ul>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->

app/account/templates/_profile_tab_accesskey.html
<!-- tab pane Access Token -->
<div class="tab-pane {{ 'active' if anchor == 'access-token' }}" id="access-token">
    <div class="callout callout-warning">
        <h5>
            <i class="icon fa fa-warning"></i> {{ _('This token is for personal use and should not be shared! Use it wisely.') }}
        </h5>
    </div>
    <div class="row">
        <div class="col-md-10 col-md-offset-1 text-center" id="code"><i
                class="fa fa-fw fa-key"></i> <code>{{ current_user.access_token }}</code>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <a href="{{ url_for('account_blueprint.route_regenerate_key') }}">
                <button type="button" class="btn btn-primary pull-right">
                    <i class="fa fa-refresh"></i> {{ _('Regenerate Key') }}
                </button>
            </a>
            <button type="button" class="btn btn-success pull-right"
                    onclick="copyTextToClipboard(document.getElementById('code'))"
                    style="margin-right: 5px;"><i class="fa fa-copy"></i> {{ _('Copy Key') }}
            </button>
        </div>
    </div>
</div>
<!-- /.tab-pane -->

app/account/templates/_profile_tab_activity.html
{% macro activity_request(time,user_request) %}
    <!-- timeline item -->
    <li>
        <i class="fa fa-upload bg-orange"></i>

        <div class="timeline-item">
            <span class="time"><i class="fa fa-clock-o"></i> {{ time }}</span>

            <h3 class="timeline-header"><a href="
                                    {{ url_for('home_blueprint.assignments', name=user_request.assignment.name) }}">{{ _('Request') }}</a>
                {{ _('sent to') }} {{ user_request.assignment.title }}</h3>

            <div class="timeline-body">
                {{ _('You sent a Request with ID') }} <a
                    href="{{ url_for('home_blueprint.requests', id=user_request.id) }}">#{{ user_request.id }}</a>
                {{ _('for the Assignment') }} <b>{{ user_request.assignment.title }}</b>
            </div>
            <div class="timeline-footer">
                {{ _('Status for this request is') }} <span
                    class="label {{ user_request.status.label }}">{{ user_request.status.name }}</span>
            </div>
        </div>
    </li>
    <!-- END timeline item -->
{% endmacro %}

{% macro activity_registered(time) %}
    <!-- timeline item -->
    <li>
        <i class="fa fa-user bg-green"></i>

        <div class="timeline-item">
            <span class="time"><i class="fa fa-clock-o"></i> {{ time }}</span>

            <h3 class="timeline-header no-border"><a
                    href="#">{{ _('Registered') }}</a> {{ _('you joined Pizarra') }}
            </h3>
        </div>
    </li>
    <!-- END timeline item -->
{% endmacro %}

{% macro activity_badge(time, badge) %}
    <!-- timeline item -->
    <li>
        <i class="fa fa-trophy bg-blue"></i>

        <div class="timeline-item">
            <span class="time"><i class="fa fa-clock-o"></i> {{ time }}</span>

            <h3 class="timeline-header"><a href="#">{{ _('Badge') }}</a> {{ _('earned') }}</h3>

            <div class="timeline-body">{{ _('You earned the Badge') }} <b>{{ badge.title }}</b>
            </div>

            <div class="timeline-footer">
                <div class="direct-chat-msg">
                    <!-- /.direct-chat-info -->
                    <img class="direct-chat-img" style="border-radius: unset;"
                         src="{{ url_for('base_blueprint.static',filename=STATIC_PZ + badge.image) }}"
                         alt="{{ _('Badge Image') }}"><!-- /.direct-chat-img -->
                    <div class="direct-chat-text">
                        {{ badge.description }}
                    </div>
                    <!-- /.direct-chat-text -->
                </div>

            </div>
        </div>
    </li>
    <!-- END timeline item -->
{% endmacro %}

<!-- tab pane Activity -->
<div class="tab-pane {{ 'active' if anchor == None or anchor == 'activity' }}" id="activity">
    <!-- The timeline -->
    <ul class="timeline timeline-inverse">

        {% for date, items in ( activity_stream.items() | sort(reverse=True)) %}
            <!-- timeline time label -->
            <li class="time-label"><span class="bg-maroon">{{ date }}</span></li>
            {% for item in items | sort(attribute='time', reverse=True) %}
                {% if item.type == 'registered' %}
                    {{ activity_registered(item.time) }}
                {% endif %}
                {% if item.type == 'request' %}
                    {{ activity_request(item.time, item.object) }}
                {% endif %}
                {% if item.type == 'badge' %}
                    {{ activity_badge(item.time, item.object) }}
                {% endif %}
            {% endfor %}
            <!-- /.timeline-label -->
        {% endfor %}

        <li>
            <i class="fa fa-clock-o bg-gray"></i>
        </li>
    </ul>
</div>
<!-- /.tab-pane -->

app/account/templates/_profile_tab_badges.html
{% macro show_badge(badge) %}
    <div class="col-md-4">
        <!-- Widget: Badge -->
        <div class="box box-widget widget-user">
            <!-- Add the bg color to the header using any of the bg-* classes -->
            <div class="widget-user-header {{ badge.background_color }}">
                <h3 class="widget-user-username">{{ badge.title }}</h3>
                <h5 class="widget-user-desc">{{ badge.subtitle }}</h5>
            </div>

            <div class="widget-user-image">
                <img class="img-circle" src="{{ url_for('base_blueprint.static',filename=STATIC_PZ + badge.image) }}"
                     alt="User Avatar">
            </div>
            <div class="box-footer">
                <div class="row">
                    <!-- /.col -->
                    <div class="col-sm-12">
                        <div class="description-block">
                            <span class="description-text">{{ badge.description }}</span>
                        </div>
                        <!-- /.description-block -->
                    </div>
                    <!-- /.col -->
                </div>
            </div>
        </div>
        <!-- /.widget-badge -->
    </div>
    <!-- /.col -->
{% endmacro %}

<!-- tab pane Badges -->
<div class="tab-pane {{ 'active' if anchor == 'badges' }}" id="badges">
    <div class="row">
        {% for badge in current_user.badges %}
            {{ show_badge(badge) }}
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-md-12">
            <img id="doge-tooltip" class="pull-right"
                 src="{{ url_for('base_blueprint.static', filename=STATIC_PZ + 'doge-tooltip.png') }}"
                 data-container="body"
                 data-toggle="popover" data-placement="left"
                 data-content="{{ "SO SHINY!!<br/> MUCH AMAZING" if current_user.badges | count > 0
                                         else "SO EMPTY!!<br/> MUCH WORK TO DO" }}"/>
        </div>
    </div>
</div>
<!-- /.tab-pane -->

app/account/templates/_profile_tab_classgroup.html
<!-- tab pane ClassGroup -->
<div class="tab-pane {{ 'active' if anchor == 'classgroup' }}" id="classgroup">
    <div class="box-body no-padding">
        <ul class="classgroup-student-list users-list clearfix">
            {% for student in current_user.classgroup.students %}
                <li class="{{ '' if student == current_user else 'classgroup-student-other' }}">
                    <img src="{{ url_for('base_blueprint.static',filename=STATIC_PZ + student.avatar) }}"
                         alt="{{ _('User Profile Picture') }}">
                    <a class="users-list-name"
                       href="#">{{ _('You!') if student == current_user else student.name }}</a>
                    <span class="users-list-date">{{ student.username }}</span>
                </li>
            {% endfor %}
        </ul>
        <!-- /.users-list -->
    </div>
</div>
<!-- /.tab-pane -->

app/account/templates/_profile_tab_password.html
{% from 'macros.html' import render_field with context %}

<!-- tab pane Password-->
<div class="tab-pane {{ 'active' if anchor == 'password' }}" id="password">
    <form class="form-horizontal"
          action="{{ url_for('account_blueprint.route_update_password') }}"
          method="post">

        {{ form.hidden_tag() }}

        {{ render_field(form.password, _('Password'), 'password') }}

        {{ render_field(form.confirm, _('Repeat Password'), 'password') }}

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" id="submit"
                        class="btn btn-danger">{{ _('Submit') }}</button>
            </div>
        </div>
    </form>
</div>
<!-- /.tab-pane -->

app/account/templates/macros.html
{% macro render_field(field, placeholder, type) %}
    <div class="form-group {{ 'has-error' if field.errors }}">
        <label for="{{ field.id }}"
               class="col-sm-2 control-label">{{ placeholder }}</label>
        <div class="col-sm-10">
            {{ field(placeholder=placeholder, class="form-control", type="password") }}
            {% if field.errors %}
                <span class="help-block">
                {% for error in field.errors %}
                    {{ error }}
                {% endfor %}
                </span>
            {% endif %}
        </div>
    </div>
{% endmacro %}

app/account/templates/profile.html
{% extends "base_site.html" %}

{% macro tab(name, description) %}
    <li id="profile-tabs-{{ name }}" data-url="{{ name }}"
            {{ 'class=active' if anchor == None or anchor == name }}>
        <a href="#{{ name }}" data-toggle="tab">{{ description }}</a>
    </li>
{% endmacro %}

{% block title %} Profile {% endblock title %}

{% block stylesheets %}
    <!-- Specific CSS goes HERE -->
{% endblock %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            {{ _('Profile') }}
            <small>{{ _('everything about you') }}</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('account_blueprint.route_account_home') }}"><i
                    class="fa fa-user"></i> {{ _('Account') }}</a>
            </li>
            <li><a href="{{ url_for('account_blueprint.route_account_home') }}">{{ _('Profile') }}</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-md-3">

                {% include '_profile_resume.html' %}

                {% include '_profile_about_me.html' %}

            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs" id="profile-tabs">

                        {{ tab('activity', _('Activity')) }}

                        {{ tab('badges', _('Badges')) }}

                        {{ tab('classgroup', _('Group')) }}

                        {{ tab('password', _('Password')) }}

                        {{ tab('access-token', _('Access Token')) }}

                    </ul>
                    <!-- tabs -->
                    <div class="tab-content">

                        {% include '_profile_tab_activity.html' %}

                        {% include '_profile_tab_badges.html' %}

                        {% include '_profile_tab_classgroup.html' %}

                        {% include '_profile_tab_password.html' %}

                        {% include '_profile_tab_accesskey.html' %}

                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

    </section>
    <!-- /.content -->

{% endblock content %}

{% block javascripts %}

    <script>
        $("#profile-tabs li").click(function () {
            // only show doge on badges tab
            if ($(this).attr('id') === 'profile-tabs-badges') {
                setTimeout(function () {
                    $('#doge-tooltip').popover('show')
                }, 1000);
            } else {
                $('#doge-tooltip').popover('hide')
            }
            // after clicking on a Tab we change the URL of the website
            history.pushState({
                id: 'my-account'
            }, 'Pizarra - Profile | UPV', {{ url_for('account_blueprint.route_account_home') }} +$(this)[0].dataset['url']);
        });
    </script>

{% endblock %}